---
abstract: 'Implement priority queue, using pluggable engines'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  Module::Find: 0
  Test::More: 0
  ex::lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-PQ
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
